# Generated by Django 6.0.1 on 2026-02-06 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Optional course image", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Sequence within difficulty level"
                    ),
                ),
                (
                    "estimated_minutes",
                    models.IntegerField(
                        default=30, help_text="Estimated time to complete"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                    ),
                ),
                (
                    "prerequisite_module",
                    models.ForeignKey(
                        blank=True,
                        help_text="Module that must be completed first",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_modules",
                        to="courses.module",
                    ),
                ),
            ],
            options={
                "ordering": ["difficulty_level", "order"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("true_false", "True/False"),
                        ],
                        default="mcq",
                        max_length=20,
                    ),
                ),
                ("option_a", models.CharField(max_length=500)),
                ("option_b", models.CharField(max_length=500)),
                ("option_c", models.CharField(blank=True, max_length=500, null=True)),
                ("option_d", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "correct_answer",
                    models.CharField(help_text="A, B, C, or D", max_length=1),
                ),
                (
                    "difficulty_score",
                    models.IntegerField(default=50, help_text="1-100, higher = harder"),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Explanation shown after answering"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated skill tags",
                        max_length=200,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="courses.module",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("total_questions", models.IntegerField()),
                ("correct_answers", models.IntegerField()),
                ("score_percentage", models.FloatField()),
                ("time_taken_minutes", models.IntegerField()),
                (
                    "answers_json",
                    models.TextField(
                        help_text="JSON storing question_id, user_answer, is_correct"
                    ),
                ),
                (
                    "adaptive_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="courses.module",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quiz Attempts",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillGap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_score",
                    models.FloatField(help_text="Score in this skill (0-100)"),
                ),
                (
                    "recommended_action",
                    models.TextField(help_text="Recommended learning path or practice"),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_gaps",
                        to="courses.module",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_gaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Skill Gaps",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "current_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                (
                    "score",
                    models.IntegerField(
                        default=0, help_text="Best score achieved (0-100)"
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(default=0, help_text="Number of quiz attempts"),
                ),
                (
                    "time_spent_minutes",
                    models.IntegerField(
                        default=0, help_text="Total time spent on this module"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.module"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Progress",
                "unique_together": {("user", "module")},
            },
        ),
    ]
